### PR TITLE
Fix battery capacity overflow bug

### PR DESCRIPTION
**Pull request by almielczarek**

### CODE REVIEW

**Comment by almielczarek** [comment]
Should we look into using this: https://rust-num.github.io/num/num/struct.BigUint.html?

**Comment by Gerschtli** [comment]
I don't think it is neccessary to increase the maximum value higher than a u64. I can't think of a battery of this size :D

**Comment by almielczarek** [comment]
Is this what you were thinking we should do here?

**Comment by Gerschtli** [comment]
Yes, but Travis CI is failing, please fix it, so I can merge your PR.

**Comment by Gerschtli** [comment]
How is your status? Otherwise I can fix it in your branch, if you are okay with it

**Comment by almielczarek** [comment]
This should do it I think.

**Comment by Gerschtli** [comment]
Thanks a lot for the very first contribution for this project!

**Pull request merged**
