### PR TITLE
support status2d

### PR DESCRIPTION
**Pull request by oatiz**
- [status2d](https://dwm.suckless.org/patches/status2d)
 ---
image

---
[config.yaml](https://fars.ee/Tj73)

### CODE REVIEW

**Comment by Gerschtli** [comment]
Hey, sorry I did not forget you and this PR, but I am having trouble finding time to look into it, but will definitely do it, looks like a nice addition :)

**Review by Gerschtli — CHANGES_REQUESTED** [review]
Please add documentation for the new options and more information (e.g. links to the dwm patch) to the README. Maybe a screenshot at the top of the README would be cool to show, what is possible with `status2d`.

Some general thoughts: You only insert status2d styling sequences in front of the feature values, but there is no possibility to reset it afterwards (before the separator) or to style the separator with a similar config option. Also it is not possible to change the styling in the middle of the feature output. e.g.: for the network output, I want `{IPv4} · {IPv6} · {ESSID}` but IPv4 should be green and IPv6 should be blue.

AFAICT, the benefits of your new options are very limiting compared with just setting the status2d stuff directly in the template like `^c#00FF00^{IPv4}^d^ · ^c#0000FF^{IPv6}^d^ · {ESSID}` or do I miss something?

**Comment by oatiz** [comment]
> AFAICT, the benefits of your new options are very limiting compared with just setting the status2d stuff directly in the template like `^c#00FF00^{IPv4}^d^ · ^c#0000FF^{IPv6}^d^ · {ESSID}` or do I miss something?

Yeah, you're right.  Directly setting the status2d stuff should be more reasonable. 

I think this pr should be closed.

**Comment by oatiz** [comment]
The benefit of new options for status2d stuff is we can check statu2d's grammar to prevent `dwm` crashes.

**Pull request closed without merging**
